version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@db/fastapi_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
